apply plugin: 'com.android.application'
apply plugin: 'kotlin-android'

android {
    namespace 'com.teamdarkness.godlytorch'
    compileSdkVersion 34

    def versionProp = file('version.properties')
    if (versionProp.canRead()) {

        // Get properties from version.properties
        Properties versionProps = new Properties()
        versionProps.load(new FileInputStream(versionProp))

        // Increase versionCode
        def code = versionProps['VERSION_CODE'].toInteger() + 1

        // Write new versionCode to version.properties
        versionProps['VERSION_CODE'] = code.toString()
        versionProps.store(versionProp.newWriter(), null)

        defaultConfig {
            applicationId "com.teamdarkness.godlytorch"
            minSdkVersion 21
            targetSdkVersion 34
            versionCode code
            versionName "1.4.6"
            testInstrumentationRunner "androidx.test.runner.AndroidJUnitRunner"
        }
    } else {
        throw new GradleException("Could not read version.properties!")
    }

    configurations.all {
        resolutionStrategy.cacheChangingModulesFor 3600, 'seconds'
    }

    signingConfigs {
        debug {
            storeFile file("../debug-key")
            storePassword 'godlytorch'
            keyAlias 'godly'
            keyPassword 'godlytorch'
        }
        release {
            v1SigningEnabled true
            v2SigningEnabled true
        }
    }

    buildTypes {
        release {
            minifyEnabled false
            proguardFiles getDefaultProguardFile('proguard-android.txt'), 'proguard-rules.pro'
            signingConfig signingConfigs.release
        }
    }

    compileOptions {
        sourceCompatibility JavaVersion.VERSION_1_8
        targetCompatibility JavaVersion.VERSION_1_8
    }

    kotlinOptions {
        jvmTarget = "1.8"
    }

}

dependencies {
    implementation fileTree(dir: 'libs', include: ['*.jar'])
    implementation 'com.github.BRoy98:Croller:master-SNAPSHOT'
    implementation 'androidx.appcompat:appcompat:1.1.0'
    implementation 'androidx.constraintlayout:constraintlayout:1.1.3'
    implementation 'com.google.android.material:material:1.9.0'
    implementation 'androidx.legacy:legacy-support-v4:1.0.0'
    implementation 'androidx.cardview:cardview:1.0.0'

    testImplementation 'junit:junit:4.12'
    androidTestImplementation 'androidx.test:runner:1.5.2'
    androidTestImplementation 'androidx.test.espresso:espresso-core:3.5.1'

    implementation 'com.afollestad.material-dialogs:core:0.9.6.0'
    implementation "com.mikepenz:iconics-core:3.0.3@aar"
    implementation "com.mikepenz:iconics-views:3.0.0@aar"
    implementation 'com.mikepenz:google-material-typeface:3.0.1.2.original@aar'
    implementation 'com.mikepenz:fontawesome-typeface:4.7.0.2@aar'
    implementation 'com.github.nisrulz:easydeviceinfo-base:2.4.1'
    //implementation 'com.github.Stericson:RootTools:5.0'
    implementation 'com.google.firebase:firebase-core:16.0.3'
    implementation 'eu.chainfire:libsuperuser:1.1.1'
    implementation 'uk.co.chrisjenx:calligraphy:2.3.0'
    implementation "org.jetbrains.kotlin:kotlin-stdlib-jdk7:$kotlin_version"
}
repositories {
    mavenCentral()
}

apply plugin: 'kotlin-android-extensions'
apply plugin: 'com.google.gms.google-services'